version: '3.7'
services:
  ### Node #########################################
  node:
    build:
      context: ./docker/node
      args:
        - NODE_VERSION=17-alpine
    container_name: 'svelte_note_node'
    volumes:
      - ./:/app
    ports:
      - '4000:4000'
      - '5432:5432'
    tty: true
